name: persistent_bottom_nav_bar_example_project
description: An example project for persistent_bottom_nav_bar

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_colorful_tab: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  persistent_bottom_nav_bar:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/nav-btn-0.png
    - assets/images/icon_minapay.png
    - assets/images/background.png
    - assets/images/BG.png
    - assets/images/bg2.png
